import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

path = "C:/Users/jerem/Desktop/Chart_Spreadsheet_2021/Spreadsheet for the preparation of Energy Reports ver-9_Update_returned_4Oct22.xlsx"
file = pd.read_excel(path, sheet_name="Growth 2010-2021", header=44, index_col=1)

df = file.iloc[2:3, 2:14]
df = df.T
years = [i for i in df.index]
electricity_Gen_PUC = [round(e) for e in df['Electricity Generation by PUC']]

dict_year_elec = {'Year': years, 'Electricity Generated by PUC [GWh]': electricity_Gen_PUC}
new_df = pd.DataFrame(dict_year_elec)
print(new_df)
plt.figure(figsize=(9, 6))
ax = sns.barplot(x=new_df['Year'], y=new_df['Electricity Generated by PUC [GWh]'], palette='Blues')
plt.title('Total Electricity Generation\n (PUC + Wind + Solar PV)', fontweight="bold")

for container in ax.containers:
    ax.bar_label(container)

path_savefig = "C:/Users/jerem/Desktop/Chart_Spreadsheet_2021/Figure/Trend_Electricity_2010-2021"
plt.savefig(f'{path_savefig}/barchart_spread_TotalGen.png', transparent=True, dpi=300)
plt.show()
